apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tomcat.name" . }}
    helm.sh/chart: {{ include "tomcat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: tomcat
  selector:
    app.kubernetes.io/name: {{ include "tomcat.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
