apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    helm.sh/chart: {{ include "zookeeper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2181
      protocol: TCP
      name: zk
  selector:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
